let print = require("./utils/logger2");


let loadgenie = ['AuctionTime.com', 'AutoTrader.com', 'Call In', 'CallShaper - List 1', 'Carmax.com', 'Cars.com', 'Criaglist.com', 'Customer Referral', 'Customer Referral', 'DependableRelocation.com', 'DiscountCarShippers.com', 'Edge', 'Enterprise NVA Program', 'FRONTER - Denise', 'FRONTER AMANDA', 'FRONTER JENN', 'FRONTER-Pam', 'FRONTER-Sharon', 'Family Friend', 'Fonter - Corrine', 'FoodTruckTransport.com', 'Fronter - Aaron', 'Fronter - Bernisse', 'Fronter - BillieJean', 'Fronter - Bobby', 'Fronter - Brandon', 'Fronter - Bryant', 'Fronter - Cievan', 'Fronter - Danniel', 'Fronter - Dave B', 'Fronter - David M', 'Fronter - Dennis', 'Fronter - Destiny', 'Fronter - Dillon', 'Fronter - Erica', 'Fronter - Erica M', 'Fronter - German', 'Fronter - James', 'Fronter - Jay', 'Fronter - Jen P', 'Fronter - Jerry', 'Fronter - Jesus', 'Fronter - Joe B', 'Fronter - John Delgado', 'Fronter - Jose Blanch', 'Fronter - Joseph C', 'Fronter - Juan Urzola', 'Fronter - Larry', 'Fronter - Leighann', 'Fronter - Linda', 'Fronter - Louis', 'Fronter - Marc', 'Fronter - Marcus', 'Fronter - Mark G', 'Fronter - Matt', 'Fronter - Miele', 'Fronter - Mike R', 'Fronter - Nadir', 'Fronter - Nick Longley', 'Fronter - Pam', 'Fronter - Robert', 'Fronter - Sam', 'Fronter - Sean', 'Fronter - Sergio', 'Fronter - Sheralyn', 'Fronter - Stuart', 'Fronter - Terry', 'Fronter - Vinny', 'Fronter - Willie', 'Fronter ALEXIS', 'Fronter Dondene', 'Fronter John Messina', 'Fronter LUCKY', 'Fronter Louis', 'Fronter SUE', 'Fronter- Hayley', 'Fronter-Max', 'Fronter-Susie', 'Frontier - Marcus', 'Frontier-Max', 'Gateway Classics', 'Given to me by Rite Way -house acct', 'Google', 'Google Search', 'Google.com', 'HeavyHauling.com', 'LowPriceAutoTransport.com', 'MLDM', 'MobileFoodTruckNews.com', 'NeedaHauler.com', 'OVE.com', 'PPC-CA', 'Quick Quote from our Website', 'Quotes Main Toll Free', 'Repeat Customer', 'Returning Customer', 'Reynolds', 'Rite Way House Acct', 'Rite Way Main Website', 'Rock&Dirt.com', 'Self Front', 'State Wide Websites', 'Streetside Classics AZ', 'Streetside Classics DFW', 'Streetside Classics FL', 'Streetside Classics NC', 'Streetside Classics Nashville', 'The Appraisal Lane', 'Trade Show', 'Unknow', 'Unverified', 'Visibility Posting', 'Walk-in', 'Website Order', 'Wheeler Dealer', 'YP.com', 'eMail Blast', 'test', 'uShip- Direct', 'uShip- M', 'uShip- PR'];

let fd = ['Americas Car Shippers', 'Artisan Call-In', 'ASQ', 'AutoTrader', 'AutoTrader.com', 'AYA', 'Bing', 'Call In', 'CallShaper - List 1', 'CARMAX.com', 'Cars.com', 'Christopher Rapoport', 'Criaglist.com', 'Customer Referall', 'Customer Referral', 'DependableRelocation.com', 'Email', 'eMail Blast', 'Enterprise NVA Program', 'Facebook', 'Family Friend', 'Family/Friend', 'Family/Friend Referral', 'Fonter - Corrine', 'Fonter LUCKY', 'FoodTruckTransport.com', 'Fronter - Aaron', 'Fronter - Angelica', 'Fronter - Bernisse', 'Fronter - BillieJean', 'Fronter - Bobby', 'Fronter - Brandon', 'Fronter - Bryant', 'Fronter - Cievan', 'Fronter - Danniel', 'Fronter - Dave B', 'Fronter - David M', 'FRONTER - Denise', 'Fronter - Dennis', 'Fronter - Destiny', 'Fronter - Dillon', 'Fronter - Erica', 'Fronter - Erica M', 'Fronter - German', 'Fronter - James', 'Fronter - Jaun Urzola', 'Fronter - Javier', 'Fronter - Jay', 'Fronter - Jen P', 'Fronter - Jerry', 'Fronter - Jesus', 'Fronter - Joe B', 'Fronter - John Delgado', 'Fronter - John Smith', 'Fronter - Jose Blanch', 'Fronter - Joseph C', 'Fronter - Juan Urzola', 'Fronter - Kenny D', 'Fronter - Larry', 'Fronter - Leighann', 'Fronter - Linda', 'Fronter - Louis', 'Fronter - Luis', 'Fronter - Marc', 'Fronter - Marcus', 'Fronter - Mark G', 'Fronter - Matt', 'Fronter - Miele', 'Fronter - Mike R', 'Fronter - Nadir', 'Fronter - Nick Longley', 'Fronter - Pam', 'Fronter - Ricardo', 'Fronter - Richard', 'Fronter - Robert', 'Fronter - Sam', 'Fronter - Sean', 'Fronter - Sergio', 'Fronter - Sheralyn', 'Fronter - Stuart', 'Fronter - Terry', 'Fronter - Vinny', 'Fronter - Willie', 'Fronter ALEXIS', 'FRONTER AMANDA', 'Fronter Dondene', 'FRONTER JENN', 'Fronter John Messina', 'Fronter Louis', 'Fronter LUCKY', 'Fronter SUE', 'Fronter- Hayley', 'Fronter-Max', 'FRONTER-Pam', 'FRONTER-Sharon', 'Fronter-Susie', 'Frontier - Marcus', 'Frontier-Max', 'Gateway Classics', 'Given to me by Rite Way -house acct', 'Google', 'Google Search', 'Google.com', 'Holidays Campaign', 'Jose Blanch', 'Lead', 'Live Chat', 'Live Chat/Website', 'LOU', 'MLDM', 'OVE.com', 'Phone', 'Phone Call', 'PPC Campaign', 'PPC-CA', 'Quick Quote from our Website', 'Quotes Main Toll Free', 'Repeat Customer', 'Returning Customer', 'Reynolds', 'Rite Way House Acct', 'Rite Way Main Website', 'Rock&Dirt.com', 'Self Front', 'Standby Order', 'Streetside Classics AZ', 'Streetside Classics DFW', 'Streetside Classics FL', 'Streetside Classics Nashville', 'Streetside Classics NC', 'test', 'The Appraisal Lane', 'Trade Show', 'Transport Reviews', 'Unverified', 'uShip', 'uShip- Direct', 'uShip- M', 'uShip- PR', 'uShip-Lead', 'Visibility Posting', 'Walk-in', 'Website', 'Website Order', 'Yellow Pages', 'Yelp', 'YP.com']

let isExist = false;
let res = [];
for (const fd_one of fd) {
    for (const ld of loadgenie ) {
        if(fd_one == ld){
            isExist = true;
            break;
        }
    }
    if(!isExist){
      res.push(fd_one);
    }
    isExist = false;
}

    console.log("-----------------")
console.log(res.length);
  // print(JSON.stringify(res));
